version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secretsecret
      MYSQL_USER: demo
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: demo
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf:/etc/mysql/conf.d
